### ISSUE TITLE
typescript changeSize and changePosition

### ISSUE THREAD

**Issue by rads17** [overwolf/pubg-dev-challenge-samples#4]
Seems to be an error in the overwolf.d.ts file for changeSize and changePosition signatures for the callbacks missing an result : any parameter?

**Comment by tomwolfgang** [comment]
Correct, the file creation is still in progress.
For most (almost all) callbacks, you should expect:

enum OWCallbackStatus {
  success = "success",
  error = "error
}

interface OWCallback {
  status: OWCallbackStatus;
  error: string | undefined;
}

Some callback parameters either inherit from OWCallback, in some situations, they don't conform to the OWCallback parameter.

**Comment by davidzoltan** [comment]
Updated the file with the correct signature. 
Thanks for the feedback.
