### ISSUE TITLE
Allow extensions to render ports or # routes

### ISSUE THREAD

**Issue by ChrisCates** [overwolf/pubg-dev-challenge-samples#5]
![error_1](https://user-images.githubusercontent.com/1561091/54063164-c37cfb00-41d8-11e9-9f6a-5047d25ea748.png)
![error_2](https://user-images.githubusercontent.com/1561091/54063165-c37cfb00-41d8-11e9-8c79-2e1303d26cbc.png)

For development reasons. It would be ideal to render webpages from localhost.
Unfortunately, the manifest file only allows you to use static files.

This also applies for 0.0.0.0 and the machine's IP as well.
Something necessary for other frameworks is query strings and hash based routing.

This doesn't seem to work when you unpack Overwolf extensions and drop in the manifest.json.

There is no real way to integrate a multi-window Angular app into Overwolf (or multi-window Vue.js app) unless you support hash routes.

The alternative is to build multiple projects at once with `ng build`, but, that's logistically not ideal and something I'd prefer not to create a Pull Request for.

**Comment by tomwolfgang** [comment]
We plan on releasing this capability to our developers channel, next week (version 127)

**Comment by ChrisCates** [comment]
Perfect, thank you!
I dont think I was added there yet.

Feel free to add me when you can (hello@chriscates.ca).
